%YAML:1.0
---
# EuRoC Dataset Configuration for Lightweight VIO
# This configuration file contains all tunable parameters for the VIO system
# Adjust these values based on your dataset characteristics and performance requirements

# Feature Detection Parameters
# Controls how corner features are detected using goodFeaturesToTrack
feature_detection:
  max_features: 200           # Maximum number of features to track per frame
  quality_level: 0.5         # Minimum accepted quality of corners (0.01 = 1% of best corner)
  min_distance: 30.0          # Minimum distance between features in pixels (prevents clustering)
  
  # Grid-based feature distribution parameters
  grid_cols: 20               # Number of grid columns for feature distribution
  grid_rows: 10               # Number of grid rows for feature distribution  
  max_features_per_grid: 2   # Maximum features allowed per grid cell

# Optical Flow Tracking Parameters  
# Controls Lucas-Kanade optical flow for feature tracking between frames
optical_flow:
  window_size: 21             # Size of search window (21x21 pixels) for frame-to-frame tracking
  max_level: 3                # Number of pyramid levels (0 = no pyramid, 3 = 4 levels total)
  max_iterations: 30          # Maximum iterations for iterative LK algorithm
  epsilon: 0.01               # Convergence criteria - stop when change < epsilon
  error_threshold: 30.0       # Maximum tracking error to accept a match (pixels)
  max_movement: 100.0         # Maximum pixel movement between frames (rejects large jumps)
  min_eigen_threshold: 1e-2   # Minimum eigenvalue threshold for optical flow

# Outlier Rejection Parameters
# Multi-stage outlier filtering to improve tracking robustness  
outlier_rejection:
  fundamental_threshold: 5.0  # RANSAC threshold for fundamental matrix (pixels) - increased from 1.0
  fundamental_confidence: 0.95 # Confidence level for RANSAC fundamental matrix estimation - decreased from 0.99
  max_movement_distance: 50.0 # Maximum allowed movement distance (pixels) in outlier check - increased from 50.0
  max_velocity_change: 30.0   # Maximum change in velocity between frames (pixels) - increased from 100.0
  min_points_for_ransac: 8    # Minimum points required to estimate fundamental matrix

# Stereo Matching Parameters
# Controls stereo correspondence matching between left/right images
# Uses dynamically estimated fundamental matrix for epipolar constraint
stereo_matching:
  # Optical flow parameters for stereo matching (different from frame-to-frame tracking)
  window_size: 31             # Search window size for stereo optical flow (larger for robustness)
  max_level: 4                # Pyramid levels for stereo optical flow (more levels for better matching)
  max_iterations: 50          # Max iterations for stereo optical flow (more for convergence)
  min_eigen_threshold: 1e-3   # Lower eigenvalue threshold for stereo (more permissive)
  
  # Stereo matching thresholds
  error_threshold: 20.0       # Maximum optical flow error for stereo matches (pixels)
  min_disparity: 1          # Minimum disparity (pixels) - filters out very far points
  max_disparity: 100.0        # Maximum disparity (pixels) - filters out very close points  
  max_y_difference: 50.0      # Maximum Y-coordinate difference for stereo pairs (pixels)
  epipolar_threshold: 1.0     # Maximum distance from epipolar line using estimated F matrix (pixels)

# Global Depth Parameters
# Controls depth validation throughout the entire VIO system
depth:
  min_depth: 0.1              # Minimum depth for valid 3D points (meters) - used in all depth validation
  max_depth: 100.0            # Maximum depth for valid 3D points (meters) - used in all depth validation

# Triangulation Parameters
# Controls 3D point generation from stereo matches
triangulation:
  max_reprojection_error: 1.0 # Maximum reprojection error for valid triangulation (pixels)
  min_parallax: 0.5           # Minimum parallax angle for reliable triangulation (degrees)

# Camera Parameters (EuRoC dataset specific)
# Image dimensions and processing parameters
camera:
  image_width: 752            # Image width in pixels (EuRoC standard)
  image_height: 480           # Image height in pixels (EuRoC standard)  
  border_size: 1              # Border size to exclude from feature detection (pixels)
  baseline: 0.110073813            # Stereo baseline in meters (EuRoC dataset)
  
  # Left camera (cam0) intrinsics
  left_intrinsics: [458.654, 457.296, 367.215, 248.375]  # [fx, fy, cx, cy]
  left_distortion: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]  # [k1, k2, p1, p2]
  
  # Right camera (cam1) intrinsics  
  right_intrinsics: [457.587, 456.134, 379.999, 255.238]  # [fx, fy, cx, cy]
  right_distortion: [-0.28368365, 0.07451284, -0.00010473, -3.55590700e-05]  # [k1, k2, p1, p2]
  
  # Left camera extrinsics (T_BC - camera to body transform)
  left_T_BC: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
              0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
              -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
              0.0, 0.0, 0.0, 1.0]
  
  # Right camera extrinsics (T_BC - camera to body transform)
  right_T_BC: [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
               0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
               -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
               0.0, 0.0, 0.0, 1.0]

# Keyframe Parameters
# Controls when new keyframes are created
keyframe:
  interval: 1                # Create keyframe every N frames

# Pose Optimization Parameters
# Controls Ceres-based pose optimization behavior
pose_optimization:
  max_iterations: 10               # Maximum optimization iterations
  function_tolerance: 1e-6         # Function tolerance for convergence
  gradient_tolerance: 1e-10        # Gradient tolerance for convergence  
  parameter_tolerance: 1e-8        # Parameter tolerance for convergence
  
  # Robust kernel parameters
  use_robust_kernel: true          # Enable robust kernel for outlier handling
  huber_delta_mono: 5.99          # Huber kernel threshold for monocular reprojection error (sqrt(chi2_2dof_95%))
  huber_delta_stereo: 7.81        # Huber kernel threshold for stereo reprojection error (sqrt(chi2_3dof_95%))
  
  # Outlier detection
  enable_outlier_detection: true   # Enable ORB-SLAM style outlier detection
  outlier_detection_rounds: 1      # Number of optimization rounds with outlier detection
  
  # Logging
  enable_solver_logging: false    # Enable Ceres solver logging (PER_MINIMIZER_ITERATION vs SILENT)
  minimizer_progress_to_stdout: false  # Print Ceres solver progress
  print_summary: false             # Print optimization summary

# Performance Parameters
# Debug and timing control flags
performance:
  enable_timing: true         # Print timing information for performance analysis
  enable_debug_output: true   # Print debug messages and feature counts
