%YAML:1.0
---
# EuRoC Dataset Configuration for Lightweight VIO

# System Mode Configuration
# Controls whether to run as VO (Visual Odometry) or VIO (Visual-Inertial Odometry)
system_mode:
  mode: "VIO"                    # Options: "VO" or "VIO"
  

# Keyframe and Windowing Parameters
# Controls keyframe selection and sliding window management
keyframe_management:
  keyframe_window_size: 5
  grid_coverage_ratio: 0.7  # Add keyframe when coverage drops to 80% of last keyframe's coverage
  time_threshold: 0.5   # Same as VO for consistency when IMU is not available   
# Feature Detection Parameters
# Controls how corner features are detected using goodFeaturesToTrack
feature_detection:
  max_features: 200           # Maximum number of features to track per frame
  quality_level: 0.01        # Minimum accepted quality of corners (0.01 = 1% of best corner)
  min_distance: 30.0          # Minimum distance between features in pixels (prevents clustering)
  
  # Grid-based feature distribution parameters
  grid_cols: 20               # Number of grid columns for feature distribution
  grid_rows: 10               # Number of grid rows for feature distribution  
  max_features_per_grid: 4   # Maximum features allowed per grid cell

# Optical Flow Tracking Parameters  
# Controls Lucas-Kanade optical flow for feature tracking between frames
optical_flow:
  window_size: 21             # Size of search window (21x21 pixels) for frame-to-frame tracking
  max_level: 3                # Number of pyramid levels (0 = no pyramid, 3 = 4 levels total)
  max_iterations: 30          # Maximum iterations for iterative LK algorithm
  epsilon: 0.01               # Convergence criteria - stop when change < epsilon
  error_threshold: 30.0       # Maximum tracking error to accept a match (pixels)
  max_movement: 100.0         # Maximum pixel movement between frames to accept tracking (pixels)
  min_eigen_threshold: 1e-3   # Minimum eigenvalue threshold for optical flow
  F_threshold: 1.0            # Fundamental matrix RANSAC distance threshold (pixels)

# Stereo Matching Parameters
# Controls stereo correspondence matching between left/right images
# Uses dynamically estimated fundamental matrix for epipolar constraint
stereo_matching:
  # Optical flow parameters for stereo matching (different from frame-to-frame tracking)
  window_size: 31             # Search window size for stereo optical flow (larger for robustness)
  max_level: 4                # Pyramid levels for stereo optical flow (more levels for better matching)
  max_iterations: 50          # Max iterations for stereo optical flow (more for convergence)
  min_eigen_threshold: 1e-4   # Lower eigenvalue threshold for stereo (more permissive)
  
  # Stereo matching thresholds
  error_threshold: 50.0       # Maximum optical flow error for stereo matches (pixels)
  min_disparity: 0.1          # Minimum disparity (pixels) - filters out very far points
  max_disparity: 300.0        # Maximum disparity (pixels) - filters out very close points  
  max_y_difference: 100.0      # Maximum Y-coordinate difference for stereo pairs (pixels)
  epipolar_threshold: 1.0     # Maximum distance from epipolar line using estimated F matrix (pixels)

# Global Depth Parameters
# Controls depth validation throughout the entire VIO system
depth:
  min_depth: 0.1              # Minimum depth for valid 3D points (meters) - used in all depth validation
  max_depth: 100.0            # Maximum depth for valid 3D points (meters) - used in all depth validation

# Triangulation Parameters
# Controls 3D point generation from stereo matches
triangulation:
  max_reprojection_error: 2.447651936 # Maximum reprojection error for valid triangulation (pixels) - sqrt(5.991) for chi2 95% with 2 DOF
  min_parallax: 0.1           # Minimum parallax angle for reliable triangulation (degrees)

# Camera Parameters (EuRoC dataset specific)
# Image dimensions and processing parameters
camera:
  image_width: 752            # Image width in pixels (EuRoC standard)
  image_height: 480           # Image height in pixels (EuRoC standard)  
  border_size: 1              # Border size to exclude from feature detection (pixels)
  
  # Left camera (cam0) intrinsics
  left_intrinsics: [458.654, 457.296, 367.215, 248.375]  # [fx, fy, cx, cy]
  left_distortion: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]  # [k1, k2, p1, p2]
  
  # Right camera (cam1) intrinsics  
  right_intrinsics: [457.587, 456.134, 379.999, 255.238]  # [fx, fy, cx, cy]
  right_distortion: [-0.28368365, 0.07451284, -0.00010473, -3.55590700e-05]  # [k1, k2, p1, p2]
  
  # Left camera extrinsics (T_BC - camera to body transform)
  left_T_BC: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
              0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
              -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
              0.0, 0.0, 0.0, 1.0]
  
  # Right camera extrinsics (T_BC - camera to body transform)
  right_T_BC: [0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
               0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
               -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
               0.0, 0.0, 0.0, 1.0]

# Optimization Parameters
# Controls Ceres-based optimization behavior for both PnP and Sliding Window
optimization:
  # PnP Optimization Parameters
  max_iterations: 10               # Maximum optimization iterations for PnP
  sliding_window_max_iterations: 4  # Maximum optimization iterations for sliding window
  function_tolerance: 1e-6         # Function tolerance for convergence
  gradient_tolerance: 1e-10        # Gradient tolerance for convergence  
  parameter_tolerance: 1e-8        # Parameter tolerance for convergence
  
  # Robust kernel parameters
  use_robust_kernel: true          # Enable robust kernel for outlier handling (delta=5.991 hardcoded)
  
  # Outlier detection (mainly for PnP)
  enable_outlier_detection: true   # Enable outlier detection
  outlier_detection_rounds: 4      # Number of optimization rounds with outlier detection
  
  # Information weighting parameters
  pnp_max_observation_weight: 3.0          # Maximum weight multiplier for PnP optimization
  sliding_window_max_observation_weight: 1.0  # Maximum weight multiplier for sliding window



# Gravity Estimation Parameters (VIO mode only)
# Controls initial gravity direction estimation from visual-IMU alignment
gravity_estimation:
  enable: true                   # Enable gravity estimation in VIO mode
  min_frames_for_estimation: 10  # Minimum number of frames before attempting gravity estimation
  gravity_magnitude: 9.81        # Expected gravity magnitude (m/s²)

# IMU Noise Model Parameters
# Inertial sensor noise characteristics for preintegration
imu_noise:
  gyroscope_noise_density: 1.6968e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 1.9393e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 2.0000e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 3.0000e-3    # [ m / s^3 / sqrt(Hz) ]   ( accel bias diffusion )





# Performance Parameters
# Debug and timing control flags
performance:
  enable_timing: true         # Print timing information for performance analysis
  enable_debug_output: true   # Print debug messages and feature counts

